version: 2.1

orbs:
  python: circleci/python@1.3.3
  azure-cli: circleci/azure-cli@1.1.0
  azure-acr: circleci/azure-acr@0.2.0

workflows:
  test-build-push-image:
    jobs:
      login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest 
      - azure-acr/build-and-push-image:
          login-server-name: devopsupskillregistrylpwwq.azurecr.io
          registry-name: devopsupskillregistrylpwwq
          repo: devops-bookstore-api
          tag: '1.$CIRCLE_BUILD_NUM'
          requires:
            - "python/test"
